### ISSUE TITLE
Thought on district and jurisdiction ids

### ISSUE THREAD

**Issue by patcon** [opencivicdata/opencivicdata#13]
Wasn't sure where to voice this concern in a place with longevity, but I just wanted to voice slight concern with the choice of using IDs with an indeterminate number of slashes in them.

For intuitive RESTful APIs, my understanding is that this is a format widely accepted and common:

```
https://api.example.com/organizations/12345/members/1234/stars
```

In order build endpoints of any depth (like that above), the uuids need to be predictable. Right now, the division_id and jurisdiction_id have a variable number of subparts delimited by slashes, so they can only be used in query params or as the final url param. This might seem particularly inconvenient as they are the highest level, and so the most sensible to place as left-most url parameters.

Of course, it's always possible to only have APIs that don't go past a uuid in depth, but sometimes this is constraining

Anyhow, thanks for everything you've done guys. For now, I'll just plan to avoid using these two IDs in the URL

**Comment by patcon** [comment]
Oh hey, and if this is ever up for reconsideration, I would absolutely love to see a standard that hashes these messier IDs in a predictable way into a UUID :)

**Comment by jpmckinney** [comment]
We're far beyond the possibility of removing slashes from division IDs (same situation when this issue was opened in 2015).
