### ISSUE TITLE
Write a merge util

### ISSUE THREAD

**Issue by paultag** [opencivicdata/opencivicdata#2]
to merge people (also orgs?)

**Comment by boblannon** [comment]
i'm working on one on my fork, FYI

**Comment by boblannon** [comment]
cf 

https://github.com/influence-usa/scrapers-us-federal/blob/disclosures/scripts/merge_dupes.py

https://github.com/influence-usa/pupa/blob/disclosures/pupa/utils/model_ops.py

WIP, of course

**Comment by paultag** [comment]
awesome! Thanks, @boblannon

**Comment by rshorey** [comment]
addressed in https://github.com/opencivicdata/python-opencivicdata-django/pull/46, which has a migration issue that needs to be fixed, probably by someone who hasn't swapped from django 1.7 to django 1.8 as many times as I have.

**Comment by rshorey** [comment]
resolved by #46
